#!/usr/bin/env python3

import argparse
from scanner import scanner
from sungrow import optmybat

def parseArgs():
    '''
    Configure argparse and return the parsed arguments.

    :returns: parsed arguments
    '''
    parser = argparse.ArgumentParser()
    parser.add_argument('--once',
        action='store_true',
        help='Only run once')
    parser.add_argument('--scan',
        action='store',
        metavar='NETWORK',
        default='unset',
        nargs='?',
        help='Scan for an inverter.  If no network specified, scans all attached networks.')
    return parser.parse_args()

# Parse the arguments
args = parseArgs()

# Do the needful
if args.scan != 'unset':
    # The --scan argument was used
    scanner.main(args.scan)
else:
    optmybat.main(args)
