#!/usr/bin/env python3
#
# Copyright 2024 Magus Verde
#
# The main entry point for optmybat.
#
# This file is part of Optmybat.
#
# Optmybat is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Optmybat is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
#
# NO AI TRAINING: Any use of this code related to the development, or training
# of AI systems is explicitly prohibited. Personal use, indexing for Internet
# search engines, etc. is intended, permitted and encouraged.
#
# You can review the GNU Affero General Public License at <https://www.gnu.org/licenses/>.

import argparse
from tools import reset, scanner, status
from sungrow import optmybat

def parseArgs():
    '''
    Configure argparse and return the parsed arguments.

    :returns: parsed arguments
    '''
    parser = argparse.ArgumentParser()
    choices = parser.add_mutually_exclusive_group()
    choices.add_argument('--once',
        action='store_true',
        help='Only run once')
    choices.add_argument('--reset',
        action='store_true',
        help='Reset everything to the default, unmanaged state')
    choices.add_argument('--status',
        action='store_true',
        help='Print out detailed status information')
    choices.add_argument('--scan',
        action='store',
        metavar='NETWORK',
        default='unset',
        nargs='?',
        help='Scan for an inverter.  If no network specified, scans all attached networks.')
    return parser.parse_args()

# Parse the arguments
args = parseArgs()

# Do the needful
if args.reset:
    # Rset the inverter to a known state
    reset.main(args)
elif args.scan != 'unset':
    # The --scan argument was used.  Scan for inverters
    scanner.main(args.scan)
elif args.status:
    # Dump the current inverter status
    status.main(args)
else:
    optmybat.main(args)
